// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_lifecycle.sql

package authqueries

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMembership = `-- name: CreateTeamMembership :exec
INSERT INTO public.users_teams (user_id, team_id, is_default, added_by)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::boolean,
    $4::uuid
)
`

type CreateTeamMembershipParams struct {
	UserID    uuid.UUID
	TeamID    uuid.UUID
	IsDefault bool
	AddedBy   *uuid.UUID
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, createTeamMembership,
		arg.UserID,
		arg.TeamID,
		arg.IsDefault,
		arg.AddedBy,
	)
	return err
}
